In [13]:
import numpy as np

In [14]:
# python list
a = [1,2,3,4,5,6,7,8,9]
sum(a)

45

In [15]:
# numpy array
A = np.array([1,2,3,4,5,6,7,8,9])
A.sum()
A.mean()


5.0

In [16]:
# matrix 
b= np.array([(1,5,6),(6,7,8)])
b

array([[1, 5, 6],
       [6, 7, 8]])

In [18]:
c = np.array([(1,5,6),(6,7,8)],dtype=int)
c

array([[1, 5, 6],
       [6, 7, 8]])

In [19]:
# homegenous for data types

a= np.zeros((5,4,3), dtype=int)
a

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [23]:
# range 
e=np.arange(10,50,5)
e

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
# multipulation
# a*b
# a@b
# a.dot()

In [ ]:
# default range 
rg= np.arange.default



In [ ]:
#axis - number of columns sum by rows 
b.sum(axis=0)
b.min(axis=0)
b.max(axis=0)
# cumulative sum alongb each row 
b.cumsum(axis=0)

In [ ]:
# reshape


In [38]:
# element array
arr=np.array([[1,2,3],[4,5,6]])

for i in arr:
    print(i)
    for y in i:
        print(y)
        

[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [ ]:
# sort 
np.sort(arr)

In [36]:
a = np.random.random([2,2])
a


array([[0.34702543, 0.57253002],
       [0.32868801, 0.43977456]])

In [37]:
print(a[0,1])

0.5725300229823511


In [39]:
#anynomus function)
(lambda x: x*2)(12)

24

In [42]:
list_1 = [1,2,3,4,5,6,7,8,9]
filter(lambda x: x%2==0, list_1)
list(filter(lambda x: x%2==0, list_1))



[2, 4, 6, 8]

In [43]:
list_1 = [1,2,3,4,5,6,7,8,9]
cubed = map(lambda x: pow(x,3), list_1)
list(cubed)


[1, 8, 27, 64, 125, 216, 343, 512, 729]

In [44]:
my_list = [ 1, 2, 3]
list( map( lambda x: x**2, my_list ) ) 

[1, 4, 9]

In [45]:
# filter compare the elements (condition)
my_list = [ 1, 2, 3 ]
list( filter( lambda x: x<2, my_list ) ) 


[1]

In [48]:
# reduce
from functools import reduce
my_list = [ 1, 2, 3 ]
reduce(lambda x, y: x + y, my_list) 


6

In [50]:
my_list = [ 1, 2, 4 ]
reduce(lambda x, y: x*y, my_list) 



8

In [58]:
import math

In [59]:
def area(r):
    return math.pi * (r**2)


In [60]:
radii = [2,5,7.1,0.3,10]

In [62]:
results = []
for i in radii:
    results.append(area(i))
print(results)

[12.566370614359172, 78.53981633974483, 158.36768566746147, 0.2827433388230814, 314.1592653589793]


In [ ]:
results.append(math)

In [ ]:
results = list(map(area,result))

In [ ]:
import statistics
data = [1.5,9.2,3.4,5.1,-9.4]
avg = statistics 

In [ ]:
list(filter(lambda x: x>avg,data))

In [ ]:
from functools import reduce 
my_list = [1,2,3,]
reduce(lambda)

In [ ]:
def concatentor(x,y):
    return x+" "+y

In [ ]:
reduce(concatenation, names)